### ISSUE TITLE
remove the mark of the web 

### ISSUE THREAD

**Issue by markhorsell** [Bizzle-Dapp/VanaDiel-Project#1]
![capture](https://user-images.githubusercontent.com/5276809/53904570-52a1db80-403e-11e9-854f-d49821b5c017.PNG)

**Comment by Bizzle-Dapp** [comment]
I have no idea what on earth that is! :'D

**Comment by Bizzle-Dapp** [comment]
Possible solution:
The files downloaded may be blocked by Windows, right click the file and under Properties | General you should see this:
![image](https://user-images.githubusercontent.com/36421291/53943159-66882480-40b4-11e9-88a2-eec42414a1da.png)
Unblock the file and that should do the trick!

Fingers crossed!
